export const REQUEST_ALL_PRODUCTS_SUCCESS = 'REQUEST_ALL_PRODUCTS_SUCCESS'
export const REQUEST_ALL_PRODUCTS_FAILURE = 'REQUEST_ALL_PRODUCTS_FAILURE'

export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES'

export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG'
export const ADD_TO_BAG = 'ADD_TO_BAG'

export const ADD_PRODUCTS_LIST_FILTER = 'ADD_PRODUCTS_LIST_FILTER'
export const REMOVE_PRODUCTS_LIST_FILTER = 'REMOVE_PRODUCTS_LIST_FILTER'

export const UPDATE_SORT_TYPE = 'UPDATE_SORT_TYPE'
export const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE'
export const UPDATE_SORTED_PRODUCTS_LENGTH = 'UPDATE_SORTED_PRODUCTS_LENGTH'
export const UPDATE_PAGE_NUM = 'UPDATE_PAGE_NUM'

export const ADD_RECENTLY_VIEWED = 'ADD_RECENTLY_VIEWED'