export const REQUEST_PRODUCT_BY_ID_SUCCESS = 'REQUEST_PRODUCT_BY_ID_SUCCESS'
export const REQUEST_PRODUCT_BY_ID_FAILURE = 'REQUEST_PRODUCT_BY_ID_FAILURE'

export const REQUEST_ALL_PRODUCTS_SUCCESS = 'REQUEST_ALL_PRODUCTS_SUCCESS'
export const REQUEST_ALL_PRODUCTS_FAILURE = 'REQUEST_ALL_PRODUCTS_FAILURE'

export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES'
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES'

export const REMOVE_FROM_BAG = 'REMOVE_FROM_BAG'
export const ADD_TO_BAG = 'ADD_TO_BAG'
